In [3]:
import numpy as np


In [4]:
np.__version__


'2.0.1'

In [7]:
arr = np.array([25,10,30,40,50,60])
arr

array([25, 10, 30, 40, 50, 60])

In [9]:
type(arr)

numpy.ndarray

In [10]:
type(np)

module

In [12]:
len(arr)
arr.dtype

dtype('int64')

In [13]:
arr = np.array([25,10,20,30,40,50,60])
arr

array([25, 10, 20, 30, 40, 50, 60])

In [20]:
arr[-3:]

array([40, 50, 60])

In [37]:
arr[3:4:5]

array([30])

In [43]:
arr = np.random.randint(1,9,)

In [49]:
arr = np.random.randint(400,450)

In [52]:
import random ,string


In [53]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [55]:
string.digits

'0123456789'